
server:
  port: ${PORT}

spring:
  application:
    name: booking hotels
  datasource:
    url: jdbc:mysql://${HOST}:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true