
-- TABLE FOR HOTEL STORAGE

CREATE TABLE hotel_db.tbl_hotel(
	ID_HOTEL INT NOT NULL AUTO_INCREMENT,
	HOTEL_NIT VARCHAR(20) NOT NULL,
	HOTEL_NAME VARCHAR(100) NOT NULL,
	HOTEL_ADDRESS VARCHAR(100) NOT NULL,
	HOTEL_DESCRIPTION VARCHAR(255) NOT NULL,
	HOTEL_STARS INT NOT NULL,
	CONSTRAINT PK_ID_HOTEL PRIMARY KEY (ID_HOTEL));