
--
CREATE TABLE hotel_db.tbl_booking(
	ID_BOOKING INT NOT NULL AUTO_INCREMENT,
	BOOKING_START_DATE DATE NOT NULL,
	BOOKING_END_DATE DATE NOT NULL,
	BOOKING_NUMBER_PEOPLE INT NOT NULL,
	BOOKING_HOTEL INT NOT NULL,
	CONSTRAINT PK_ID_BOOKING PRIMARY KEY (ID_BOOKING));
	
-- CREACION DE LA LLAVE FORANEA
ALTER TABLE hotel_db.tbl_booking
ADD CONSTRAINT FK_BOOKING_HOTEL
FOREIGN KEY (BOOKING_HOTEL)
REFERENCES hotel_db.tbl_hotel(ID_HOTEL);